spring:
# thymeleaf???
thymeleaf:
# ????
cache: false
# ?????
datasource:
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc::mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&ServerTimezone=Asia/Shanghai
username: root
password: root
hikari:
# ????
pool-name: DataHikariCP
# ???????
minimum-idle: 5
# ?????????????10???60000ms??????????
idle-timeout: 1800000
# ??????????10
maximum-pool-size: 10
# ?????????????
auto-commit: true
# ?????????0??????????1800000ms??????
max-lifetime: 1800000
# ?????????30000ms
connection-timeout: 30000
# ??????????????????
connection-test-query: SELECT 1

# MyBatisPlus??
mybatis-plus:
# ??Mapper.xml????
mapper-locations: classpath*:/mapper/*Mapper.xml
# ??MyBatis?????????????????
type-aliases-package: com.intern.seckilldemo.pojo


# MyBatis SQL??????????????Mapper.xml?????
logging:
level:
com.intern.seckilldemo.mapper: debug