spring:
  web:
    # 静态资源处理
    resources:
      # 启动默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          # 缓存响应时间，单位为秒
          max-age: 3600
      chain:
        # 资源链启动缓存，默认启动
        cache: true
        # 启动资源链，默认禁用
        enabled: true
        # 启用压缩资源(gzip, brotli)解析，默认禁用
        compressed: true
        # 启用h5应用缓存，默认禁用
        # html-application-cache: true
      static-locations: classpath:/static/
  # thymeleaf设置：
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&ServerTimezone=Asia/Shanghai
    username: root
    password: 056981_Gu
    hikari:
      # 连接池名
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟（60000ms），这里给了半个小时
      idle-timeout: 1800000
      # 最大连接数，默认就是10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认为1800000ms（半个小时）
      max-lifetime: 1800000
      # 连接超时时间，默认30000ms
      connection-timeout: 30000
      # 心跳机制，测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # redis配置
  redis:
    # 服务器地址（虚拟机的ip地址）
    host: 192.168.209.129
    # 端口
    port: 6379
    # 数据库编号，默认是0
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认为8
        max-active: 8
        # 最大连接默认等待时间，默认-1，即一直等下去
        max-wait: 10000ms
        # 最大空闲连接数，默认为8
        max-idle: 200
        # 最小空闲连接数，默认为0
        min-idle: 5

  # RabbitMQ
  rabbitmq:
    # 服务器
    host: 192.168.209.129
    # 用户名
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 消费者每次只能处理的消息数，处理完这么多才能继续处理下一条消息。
        prefetch: 1
        # 启动时是否默认启动容器，默认启用
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认禁用
        enabled: true
        # 重试时间，默认1000毫秒
        initial-interval: 1000ms
        # 重试最大次数，默认为3
        max-attempts: 3
        # 重试最大间隔时间，默认1000毫秒
        max-interval: 1000ms
        # 重试的间隔乘数，如果设置为2，第一次重试间隔1秒，第二次就要等待2秒，第三次等待4秒，以此类推。
        multiplier: 1



# MyBatisPlus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.intern.seckill.pojo

# MyBatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.intern.seckill.mapper: debug
